import '@/styles/index.css';

// import type { Metadata } from 'next';
import { Metadata } from 'next/types';
import React from 'react';

import { MSWComponent } from '@/mocks';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface Props {
    children: React.ReactNode;
}

const RootLayout = ({ children }: Props) => {
    return (
        <html lang='en'>
            <body>
                <MSWComponent>{children}</MSWComponent>
            </body>
        </html>
    );
};

export default RootLayout;
