name: Review Assign
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assignee to Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assigness: ${{github.actor}}
          reviewers: mingnana, bbung95, heywon0909
